# Site Settings
title: "lrabello.dev"
description: "half-baked opinions, hard-earned lessons, and hot takes on software engineering"
author: "Leo Rabello"
url: "https://lrabello.dev"
baseurl: ""

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Sass
sass:
  style: compressed
  sass_dir: _sass

# Pagination
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
